### ISSUE TITLE
Not signalling `end` event?

### ISSUE THREAD

**Issue by jednano** [rvagg/through2#30]
I would expect the following test to work, but it's not.

``` js
var through2 = require('through2');
var vfs = require('vinyl-fs');

it('passes a file along with null contents', function(done) {
  vfs.src('test/fixtures/foo.js')
    .pipe(through2.obj())
    .on('end', () => {
      done();
    });
});
```

Is this an issue with through2 or is there no issue at all? What should I expect? I'm thinking the `end` event should be fired.

**Comment by TheLudd** [comment]
I have a similar problem but neither `end` nor `finish` works for me:

```
  myMongoDbCollection.aggregate([
    ... aggregation pipeline
  ])
    .pipe(through2.obj(function (obj, _, cb) {
      this.push(turnObjIntoString(obj))
      cb()
    }))
    .pipe(process.stdout)
    .on('finish', closeDB)
    .on('error', closeDB)
```

The result is printed to `stdout` as expected but the `closeDB` function is never called and the program never exists.
If I add the listeners before I pipe, then they are called and the program is closed but the print becomes messed up.

**Comment by rvagg** [comment]
@TheLudd you're listening to events on `process.stdout`, I can't say off the top of my head but it could be that it's not going "close" for you.

```
  myMongoDbCollection.aggregate([
    ... aggregation pipeline
  ])
    .pipe(through2.obj(function (obj, _, cb) {
      this.push(turnObjIntoString(obj))
      cb()
    }))
    .on('finish', closeDB)
    .on('error', closeDB)
    .pipe(process.stdout)
```

.. maybe? also, `error` isn't propagated between `pipe()` so it's not good enough to just stick it at the end of a chain, you should listen for it on each stream in the chain that could trigger an error.

Also check out:

* https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback
* https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback

They might be helpful for various situations.

**Comment by TheLudd** [comment]
@rvagg Thanks, rearranging the last lines like this did the trick:
```
    .on('finish', closeDB)
    .on('error', closeDB)
    .pipe(process.stdout)
```

Will have to read up a bit on piping and errors....
