### ISSUE TITLE
How can I resume()/pause() a through2 stream? <-- Error: Cannot switch to old mode now.

### ISSUE THREAD

**Issue by bitliner** [rvagg/through2#35]
I have a through2 stream whose function runs

```
...
self.pause();
somethingAsyncOnChunk(chunk);
done();
...
```

and the stream is resumed when an event happens (outside the callback passed to through2.obj constructor).

But this code throws `Error: Cannot switch to old mode now.`.

I am using pause()/resume() because I cannot pass any callback to the function `somethingAsyncOnChunk(chunk)`

Apparently it is not possible to use them because the stream I have is in a pipeline (`pipe()`).
But how may I pause()/resume() the stream?

**Comment by bitliner** [comment]
The problem is that if I call done() then the stream reads the next chunks, and I have to avoid it for synchronization problems.

I was trying to call done() outside of the function of the stream (after having assigned the function done() to an outer variable ), but this throws an exception as well.

The point is: how can I pause/resume() the stream? Is it possible?

**Comment by mafintosh** [comment]
.resume/.pause throttles the *readable* end. what you are talking about is throttling the *writable* end. the way to that in streams3 is using the `cork()` method as I understand it. this isn't supported in through2 yet.

I would still implement this by waiting to call done

``` js
var stream = through(function(data, enc, cb) {
  stream.push(data)
  stream.next = function() {
    stream.next = function() {}
    cb()
  }
})

stream.write('hello')
stream.write('world')
...
stream.next()
```

**Comment by bitliner** [comment]
That throws `Error: no writecb in Transform class`, as my similar code posted above

**Comment by bitliner** [comment]
That works
