### ISSUE TITLE
end event doesn't fire unless there is an output stream for a pipe

### ISSUE THREAD

**Issue by tracker1** [rvagg/through2#37]
I have something similar to the following...

```js
...
.pipe(through2.obj(function(item, enc, cb){
  ...
  cb(null, item);
})
.on('end', function(){
  //this doesn't fire unless you un-comment the next pipe.
})
//.pipe(through2.obj())
```

I'm using through2@0.6.3, and have run it under iojs 1.0.2 and node 0.11.14, both showing the above behavior

**Comment by juliangruber** [comment]
with streams2 streams, the stream is in a pause state unless you pipe it into another stream or listen for the `data` event, which causes it to switch to streams1 mode. so this isn't a bug in this lib.

the simplest way to make this snippet work is to add `.on('data', function(){})`.

**Comment by rvagg** [comment]
Actually if you aren't piping anywhere then this doesn't make sense:  `cb(null, item);`, you're putting `item` into the buffer and it's filling up and pausing. Just make it `cb()` and the stream won't buffer and block.

**Comment by tracker1** [comment]
@rvagg I understand what you mean... I have a set of processing modules with a method that returns a through2 stream... each method does what it needs and passes through a modified item/state object.  the pipe chain is actually pretty long... I didn't know a data listener was needed for the end event to fire...

Guess this belongs here: https://github.com/iojs/io.js/issues/89#issuecomment-70928722

**Comment by mafintosh** [comment]
Instead of using a empty data listener you can also just call `.resume()`

**Comment by tracker1** [comment]
@mafintosh thanks, that works... :-)

----

for reference, here's what I'm doing...

```js
var Promise = require('i-promise')
    ,getDealerPendingStream = require('../data/get-dealer-pending-list')
    ,addDealerListings = require('./process-add-dealer-listings')
    ,calculatePayment = require('./process-payment-calculation')
    ,logTransaction = require('./process-log-transaction')
    ,updateSalesforce = require('./process-update-salesforce')
    ,runPayment = require('./process-payment')
    ,logItemOutput = require('./process-log-item-output')
    ;

module.exports = function(){
  return new Promise(function(resolve, reject) {
    getDealerPendingStream()
      .pipe(addDealerListings())
      .pipe(calculatePayment())
      .pipe(runPayment())
      .pipe(logTransaction())
      .pipe(updateSalesforce())
      .pipe(logItemOutput())
      .on('error', reject)
      .on('end', resolve)
      .resume() // needed so last stream can process data
      ;
  });
}
```
