### ISSUE TITLE
Stream loosing files

### ISSUE THREAD

**Issue by nevcos** [rvagg/through2#38]
gulp-filter is using through2 and in certain conditions [Some files are skipped during gulp.dest after restore](https://github.com/sindresorhus/gulp-filter/issues/29).

From what I've tested (see [my comment](https://github.com/sindresorhus/gulp-filter/issues/29#issuecomment-70080950)) I think that's related with an "highWaterMark" value that was introduced in version 0.5.0: https://github.com/rvagg/through2/commit/7ce8c780b1219c1ebea7717e9dc111bbe4dc2ffa

I've tested with through2 version 0.4.2 and there are no lost items (we switched to this version).
Also, tested with an highWaterMark value of 128 and it also worked. 

Thanks!

**Comment by mafintosh** [comment]
This is most like a bug in your code with a stream not being drained. Setting hwm to a higher value just means that any flushing bug will take longer to appear.

**Comment by mafintosh** [comment]
I found the bug in gulp-filter and tried to add a (somewhat) detailed description of why you are seeing this issue in sindresorhus/gulp-filter#29. Since this isn't related to though I'm closing this. Feel free to reopen if I'm wrong :)

**Comment by juliangruber** [comment]
killer job!

**Comment by nevcos** [comment]
@mafintosh thanks :)!
