### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rvagg/through2#40]
I'm doing
`dump_stream.pipe(through2({objectMode:true}, my_transformer))`

and getting this:

Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:        throw er; // Unhandled stream error in pipe. 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:              ^ 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:  Error: invalid event name: None 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at DestroyableTransform.my_transformer [as _transform] (/app/app/util/mixpanel.js:54:20) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at DestroyableTransform.Transform._read (/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at DestroyableTransform.Transform._write (/app/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at doWrite (/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at writeOrBuffer (/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at DestroyableTransform.Writable.write (/app/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at Stream.ondata (stream.js:51:26) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at Stream.emit (events.js:95:17) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at Stream.reemit (/app/node_modules/mixpanel/node_modules/event-stream/node_modules/duplexer/index.js:70:25) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at Stream.emit (events.js:95:17) 
Feb 27 16:11:20 analytics-migration app/analytics_migration_2.1:      at Stream.<anonymous> (/app/node_modules/mixpanel/node_modules/event-stream/index.js:237:12) 

My code doesn't create,subscribe,etc to any events, so I suspect this is a bug in through2?

My transformer does call its callback with an error sometimes:
`callback(new Error(chunk.error))`
But that is correct, right?

**Comment by mafintosh** [comment]
can you share a full code snippet of what you are trying to do?

**Comment by GeoffreyPlitt** [comment]
Sure:
```javascript
// This module assists in doing mixpanel export queries.

var debug = require('debug')('mixpanel');
var Promise = require('bluebird');
var config = require('../../config');
var mixpanel_lib = require('mixpanel');
var through2 = require('through2');

function YYYYMMDD(d) {
  var yyyy = d.getFullYear().toString();
  var mm = (d.getMonth() + 1).toString(); // getMonth() is zero-based
  var dd = d.getDate().toString();
  return yyyy + '-' + (mm[1] ? mm : "0" + mm[0]) + '-' + (dd[1] ? dd : "0" + dd[0]); // padding
}

function insertCommas(str) {
    var a = str.split("");
    a.reverse();

    var t, i = 0, arr = Array();

    while (t = a.shift()) { // jshint ignore:line
       if (((i++ % 3) === 0) && arr.length > 0)
           arr.unshift(",");
       arr.unshift(t);
    }

    return arr.join("");
}

var LOG_SIZE = 10000;

exports.mixpanel_query = function(event, project_id, from_date, to_date) {
  var ret = [];
  var query = {
    from_date: YYYYMMDD(from_date),
    to_date: YYYYMMDD(to_date),
    event: [event],
    where: 'properties["project_id"] == "' + project_id + '"'
  };
  return new Promise(function(resolve, reject) {
    var mx = new mixpanel_lib({
      api_key: config.mixpanel.api_key,
      api_secret: config.mixpanel.api_secret
    });
    mx.export_data(query, function(dump_stream) {
      // our transformer does a handful of things:
      // - remove the dollar signs
      // - assert the "properties" and "properties.project_id" fields exist.
      // - keep a count of chunks and debug-log the count every so often
      var count = 0;
      function my_transformer(chunk, encoding, callback) {
        if(chunk.error) {
          callback(new Error(chunk.error));
        } else {
          // these 3 lines quickly remove the dollar signs
          var chunk = JSON.stringify(chunk);
          chunk = chunk.replace(/\$/g, '');
          chunk = JSON.parse(chunk);

          if (!chunk.properties || !chunk.properties.project_id) {
            callback(new Error('Unexpected chunk format: ' + JSON.stringify(chunk)));
          } else {
            count++;
            if(count>=LOG_SIZE && (count % LOG_SIZE === 0)) {
              console.log('mixpanel_query(' + event + ', ' + project_id + '): ' + insertCommas(count.toString()) + ' rows...');
            }
            callback(null, chunk);
          }
        }
      }
      resolve(dump_stream.pipe(through2({objectMode:true}, my_transformer)));
    });
  });
}

```

**Comment by brycebaril** [comment]
Is `dump_stream` implementing its own `pipe` function, perhaps? Otherwise I'm not someone who uses Promises enough to know how those might interfere here.

However...

One thing that is missing from your code is error handling, which would be something like this:

```
var transformer = through2({objectMode: true}, my_transformer)

transformer.on("error", function handleError(err) {
  /* TODO forward the error to dump_stream, or wherever */
})

dump_stream.pipe(transformer)
```

If you look at your error, the actual error is: `Error: invalid event name: None` which would be emit as an `error` on the transform stream.

The reason I ask about the custom `pipe` implementation is that typically this error would end up from `events.js` not `stream.js` -- i.e.:

```
events.js:72
        throw er; // Unhandled 'error' event
```

However, it may just be irrelevant here.

**Comment by GeoffreyPlitt** [comment]
Cool. I think the error was due to something else, closing this.
