### ISSUE TITLE
Async issues?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [rvagg/through2#41]
Hi,

I have a bug that seems to surface only when I use the callback() function with a setTimeout/setImmediate, etc.

So basically, if I fail to call callback() before the transformer function exits, the error occurs. Is this normal? I've found that sometimes I need to call callback asynchrously if I need to do some IO first before calling it.

The error is `SynaxError: [Unexpected end of input...]" but I can't see where it's being triggered from exactly.

**Comment by mafintosh** [comment]
could you post a code example of what you are trying to do?

**Comment by brycebaril** [comment]
That's almost certainly a JSON.parse error, e.g.

```
JSON.parse('{"hi": ')
SyntaxError: Unexpected end of input
    at Object.parse (native)
```

I agree with @mafintosh -- we'll need a code example to really help you out here.

**Comment by GeoffreyPlitt** [comment]
Thanks so much for the feedback. It turned out to be something else, but it was really hard to debug and I thought it might be the async/sync nature of this module-- but it wasn't. Closing! Thanks again!
