### ISSUE TITLE
Readme on npm

### ISSUE THREAD

**Issue by peteruithoven** [rvagg/through2#42]
For some reason the [through2 npm page](https://www.npmjs.com/package/through2) doesn't show the readme?

**Comment by mattdesl** [comment]
:+1: This would be awesome. Small barriers to entry like this can be frustrating and disheartening for stream newbies (like me).

**Comment by mafintosh** [comment]
@rvagg we could just patch publish to fix this probably

**Comment by brycebaril** [comment]
Tried a patch publish to no avail, turns out this was the culprit: https://github.com/npm/newww/issues/631

Published 0.6.5 which removes block comments from the README for now until that issue is resolved.

**Comment by peteruithoven** [comment]
Thanks for figuring this out

**Comment by mafintosh** [comment]
@brycebaril awesome! :+1:

**Comment by mattdesl** [comment]
:smile: Thanks!
