### ISSUE TITLE
What is the purpose of DestroyableTransform?

### ISSUE THREAD

**Issue by bucaran** [rvagg/through2#43]
I have implemented a `through2`-like transform stream function wrapper that uses a _simpler_ interface than `through2` [here](https://github.com/bucaran/kthulhu/blob/master/README.md).

While in `through2` you do

```js
fs.createReadStream('ex.txt')
  .pipe(thru(function (chunk, enc, callback) {
    for (var i = 0; i < chunk.length; i++)
      if (chunk[i] == 97)
        chunk[i] = 122 // swap 'a' for 'z'

    this.push(chunk)

    callback()
   }))
  .pipe(fs.createWriteStream('out.txt'))
```

In mine you could:
```js
fs.createReadStream("ex.txt")
  .pipe(thru(function (chunk) {
    return chunk.map(function (value) {
      return (value == 97) ? 122 : value
    })
   }))
  .pipe(fs.createWriteStream("out.txt"))
```

I find this syntax (not necessarily adding the custom `.map()` function to the `chunk` object), but the `return` style to pass data) simpler, but there is no notion of destroying anything in my implementation. 

1. Why do I need this?
2. What do you think of yet another `through` version that accomodates for this syntax?

**Comment by juliangruber** [comment]
1. Not all streams implement `.destroy` and they also don't have to, but if they do, it's useful because you can just tell the stream "destroy yourself, i don't want to hear from you ever again"
2. The through2 syntax takes in account asynchronous operations, which makes it more generic. If all you do is sync though, for your purpose that module makes sense.

Also keep in mind that this is also valid with through2:

```js
fs.createReadStream('ex.txt')
  .pipe(thru(function (chunk, enc, callback) {
    for (var i = 0; i < chunk.length; i++)
      if (chunk[i] == 97)
        chunk[i] = 122 // swap 'a' for 'z'
    callback(null, chunk)
   }))
  .pipe(fs.createWriteStream('out.txt'))
```

**Comment by bucaran** [comment]
@juliangruber Thanks!

(1) I see, but could you name some / any use cases of having your stream destroy itself? I don't want to add this feature until I can fully understand this point.

(2) My through version _also_ takes async operations into account via promises. If you return a promise it will handle it accordingly.

**Comment by juliangruber** [comment]
1. if you don't need it, don't add it, simple as that. see also https://github.com/rvagg/through2/pull/25 for motivation in this repo
2. if that works for you, that's great

**Comment by bucaran** [comment]
@juliangruber Thanks! :smile:
