### ISSUE TITLE
Multiple outputs from transform function are not supported

### ISSUE THREAD

**Issue by asemichastnov** [rvagg/through2#44]
Hi,

Sorry in advance if I misunderstand the concept of working with the library, but I had to modify it a bit to suit my needs — probably, this can be considered as an issue.

The case was the following: the transform function resulted in several output pieces to be written. Say, I have an incoming string like "Key=1, Value=1; Key=2, Value=2". I need to split them into 
```javascript
{ Key : 1, Value : 1 }, { Key : 2, Value : 2 }.
```

The transform function reads from the stream and, once it encounters ";", it creates a new object and calls back. The problem is that by the time the callback should be called in the second time, it's already null (function afterTransform in _stream_transform does this). I had to comment lines 
```javascript
ts.writecb = null;
```
 in afterTransform and 
```javascript
strate.writecb = null;
``` 
in _stream_writable / doWrite.

**Comment by mafintosh** [comment]
Dont call the callback twice. Use `.push` instead

``` js
though(function (data, enc, cb) {
  this.push({key: 1, value: 1})
  this.push({key: 2, value: 2})
  cb()
})
```

**Comment by asemichastnov** [comment]
Thank you, it worked
