### ISSUE TITLE
Upgrade to streams3

### ISSUE THREAD

**Issue by feross** [rvagg/through2#45]
Can we bump the `readable-stream` version that this modules uses? I want to use methods like `cork` and `uncork`.

**Comment by juliangruber** [comment]
+1

**Comment by feross** [comment]
@rvagg Would you accept a PR that did this?

**Comment by rvagg** [comment]
@feross we are publishing against the `@1.0` tag for streams3 and `@latest` is for streams2, what we're missing is the latest io.js version which is still unpublished and could represent a finalized streams3

**Comment by feross** [comment]
Understood, thanks!

cc @maxogden
