### ISSUE TITLE
how to transform the data in my stream?

### ISSUE THREAD

**Issue by macscripter** [rvagg/through2#61]
First of all, thank you for your library!

I need to transform the data of my stream.

Here goes my code:

   var body = '<?xml version="1.0" encoding="utf-8"?>';

```
var stream = through2(function(chunk, enc, callback) {
var result = body;
this.push(result);
callback();
});

req.pipe(stream);
```

Is it correct? May I use this new stream?

Thank you for your help

**Comment by dcousens** [comment]
@macscripter have you read the [`README`](https://github.com/rvagg/through2/blob/master/README.md)?

It is perfectly describes the canonical examples.

**Comment by markstos** [comment]
This issue can be closed.
