### ISSUE TITLE
Transform request body

### ISSUE THREAD

**Issue by mirkods** [rvagg/through2#62]
Hi guys,
congrats for this awesome lib.

I need to transform the request body before it has been proxied. 
This is my code

``` javascript
function write(chunk, encoding, next){
  var transformed_body = new BodyHelper(JSON.parse(chunk), this.body_transformation).apply()
  this.push(JSON.stringify(transformed_body))
  next();
}

var transform = through.obj(write);
transform.body_transformation = // custom rule
req.pipe(transform).pipe(request.post(settings)).pipe(res)
```

In this example the object transformed_body is correctly formatted, but the following piping not receive the body correctly.
Instead even if I use .obj function I need to stringify the object because it throw the error Argument passed must be a string or buffer, why?

Where I'm making a mistake?

Thanks

**Comment by anko** [comment]
Are you sure the error is from the `transform` stream, and not from the others it's piped to?

At which line exactly do you get the error?

Do you have a [testable example](http://stackoverflow.com/help/mcve)?

**Comment by mirkods** [comment]
If I remove the transformation pipe all work fine. 
With the transformation seems like the request module (https://github.com/request/request) it not able to copy the body

**Comment by yoshuawuyts** [comment]
`transform.body_transformation = // custom rule` is not implemented by `through2` thus will result in a `noop`. Try updating your `write` function or implementing multiple `through` streams.

**Comment by mirkods** [comment]
@yoshuawuyts I use transform.body_transformation just to set an object in order to find it in the context

**Comment by yoshuawuyts** [comment]
oh right, I missed that. Don't do that, it's confusing.

**Comment by mirkods** [comment]
It's not clear for me why this code doesn't works

```javascript
function write(chunk, encoding, next){
  next(null, chunk);
}
var transform = through.obj(write);
req.pipe(transform).pipe(res)
```

In this example I expected that the response's body is the same of the request one because the transformation is null. Why the response body is empty?

**Comment by yoshuawuyts** [comment]
This does work, you're probably having issues in other parts of your code. Here's a minimal http example:
```js
const through = require('through2')
const http = require('http')

http.createServer(function (req, res) {
  req.pipe(through((chunk, enc, next) => next(null, chunk))).pipe(res)
}).listen(8080)
```
```sh
$ curl localhost:8080 -d hello-world
hello-world
```
I hope this helps you narrow down your issue. Cheers!
