### ISSUE TITLE
Missing CHANGELOG?

### ISSUE THREAD

**Issue by subeeshcbabu** [rvagg/through2#65]
I am upgrading the version to the latest and wondering if there are any CHANGELOG file or any similar document listing the breaking changes/features.

**Comment by yoshuawuyts** [comment]
nope, to my knowledge there is none. I think looking at the README.md files at the respective releases is the best way to find out what it is you want to know https://github.com/rvagg/through2/releases

**Comment by rvagg** [comment]
From memory, through2 hasn't really changed much over time, it's readable-stream that's changed, so depending on your versions you may be switching from streams2 to streams3. The differences are mostly transparent, at least they are intended to be.

**Comment by subeeshcbabu** [comment]
@yoshuawuyts @rvagg -Thx.
