### ISSUE TITLE
Issue getting the basics to work

### ISSUE THREAD

**Issue by justinhelmer** [rvagg/through2#67]
Hello again, @rvagg - thanks for the amazing set of tools.

I am currently using [map-stream](https://github.com/dominictarr/map-stream) by @dominictarr and am trying to convert to [through2](https://github.com/rvagg/through2) for the same functionality.

I have stripped away all of the business logic and am left with a simple pass through:

```js
pipeline.pipe(map(function(file, cb) {
  console.log('I work!');
  cb(null, file);
}));
```

I _really_ would like to use `through2`, and if I am understanding the docs correctly, this would look like:

```js
pipeline.pipe(through2(function(chunk, enc, callback) {
  this.push(chunk);
  callback();
}));
```

However, when using the above code, I am consistently getting the following error:

```bash
TypeError: Invalid non-string/buffer chunk
```

I have additionally tried [through2-map](https://github.com/brycebaril/through2-map) directly since my final solution only needs the mapping capabilities, but still no luck.

There must be something simple I am overlooking.. can you assist? I appreciate your time.

**Comment by brycebaril** [comment]
@justinhelmer what are the stream contents? 
>TypeError: Invalid non-string/buffer chunk


Usually means that you're streaming JS values, which is not the default for streams2/streams3 streams.

Try `through2({objectMode: true}, function (...)` (or the same with `through2-map`) to signal this stream is an Object stream.

**Comment by mafintosh** [comment]
You can also do `through2.obj` to turn it into object mode.

**Comment by justinhelmer** [comment]
@brycebaril @mafintosh -

Thank you both. I used `through2.obj` and it didn't work originally, but must have been for another reason because it works as I would expect it to now.

I really thought I had tried this in the same context or I would not have wasted your valuable time. 

Regardless, thanks for identifying my gap in knowledge; now I know for next time. ;-)

Cheers!
