### ISSUE TITLE
Arrow function leaves `this` undefined in code block.

### ISSUE THREAD

**Issue by sgnl** [rvagg/through2#68]
Any clarification on why this is happening?

## Misc specs
**Node version:** `5.6.0`
**strict-mode:** enabled via `'use strict'`
**through2 version:** `2.0.1`

### The Good  :+1: 

**Works fine with keyword `Function` declaration:**

```javascript

.pipe(Through2(function(chunk, enc, callback) {
        this.push(chunk)

        callback();
}))
```

### The Bad :-1: 
**Breaks when using ES2015 Arrow Function: **

```javascript
.pipe(Through2((chunk, enc, callback) => {
        this.push(chunk)

        callback();
}))
```

### The Ugly :bug:
** The error displayed in my cli: **
```
this.push(results)
            ^

TypeError: Cannot read property 'push' of undefined
  at: ...
```

*Searched through Issues and I did not find anything related. Posting here as reference for anyone that may experience the issue in the future.*

Aloha.

**Comment by sgnl** [comment]
Thankfully, I can still push data down the pipeline with  `callback(null, dataToPass)`.

```javascript
.pipe(Through2((chunk, enc, callback) => {
    //...
    callback(null, results);
}))
```

**Comment by brycebaril** [comment]
Hi @sgnl -- I believe what you are running into is how arrow functions work: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

>An arrow function expression (also known as fat arrow function) has a shorter syntax compared to function expressions and lexically binds the this value (does not bind its own this, arguments, super, or new.target).
