### ISSUE TITLE
Can I use through2 to create Writable-only stream?

### ISSUE THREAD

**Issue by jfromaniello** [rvagg/through2#72]
I generally use through2 to write transformations. Does it make sense to use it  to create a writable stream or should I use something like [writable2](https://www.npmjs.com/package/writable2)?

Thanks

**Comment by dgonzalez** [comment]
It does. A transform stream is in essence a Duplex stream (Readable and Writable) so nothing prevents you from using only the writable capabilities.

**Comment by juliangruber** [comment]
Just use node core streams directly, they have a convenient constructor api now:

```js
const { Writable } = require('stream')

const writable = Writable({
  write: (chunk, enc, done) {
    // ...
    done()
  }
})
```

**Comment by jfromaniello** [comment]
@juliangruber @dgonzalez Thank you both!
