### ISSUE TITLE
Is there a minimum node.js version required?

### ISSUE THREAD

**Issue by tdmalone** [rvagg/through2#73]
Question as per the title: is there a minimum version of node.js required to run through2?

I couldn't find it in the README either here or on the npm package page. Thanks!

**Comment by yoshuawuyts** [comment]
to my knowledge this should run in node `>=0.10`

**Comment by rvagg** [comment]
yeah, I think we only bothered testing readable-stream on v0.10, although I can't think of anything that would prevent it also working on v0.8 but really, you shouldn't be on anything older than v4 at this stage anyway
