### ISSUE TITLE
performance issues? 

### ISSUE THREAD

**Issue by loveencounterflow** [rvagg/through2#76]
I just built https://github.com/loveencounterflow/basic-stream-benchmarks to get a handle on how heavy stream transforms are. The code is quite simple:

```coffee
input         = FS.createReadStream   input_path
output        = FS.createWriteStream  output_path
#.........................................................................................................
p = input
p = p.pipe $split()
#.........................................................................................................
p = p.pipe through2.obj ( data, encoding, callback ) ->
  unless S.t0?
    start_profile S
    S.t0 ?= Date.now()
  S.byte_count += data.length
  S.item_count += +1
  @push data
  callback()
#.........................................................................................................
for _ in [ 1 .. n ] by +1
  if mode is 'sync'
    p = p.pipe through2.obj ( data, encoding, callback ) -> @push data; callback()
  else
    p = p.pipe through2.obj ( data, encoding, callback ) -> setImmediate => @push data; callback()
#.........................................................................................................
p = p.pipe through2 ( data, encoding, callback ) -> @push data + '\n'; callback()
p = p.pipe output
```

Now I may be totally wrong here and maybe there's some blunder I committed (in a way I hope so), but if
the numbers are correct then adding single stream transform with through2 may cost you like almost a second (depending on hardware, amount of data processed and so on). 

Now I'm aware that you normally won't build pipelines with hundreds of stream transforms as I do for the test, but shouldn't a no-op transform weigh in more like a no-op function call, i.e. orders of magnitude below a whole second?

The flamegraphs I produced (and that you can produce after cloning and e.g. running in Chrome DevTools)
would indicate that indeed most of the time is spent in `through2` and `readable-stream` code (have a look at them over at https://github.com/loveencounterflow/basic-stream-benchmarks#flamegraphs). 

Now I'm aware that the tests I ran process a file with ~50k lines, so each transform is called that often. Still it means that just in order to work through a run-of-the-mill 1.4MB text file I have to be prepared that adding just 10 steps to the processing will make the time required go from 4 seconds to 10 seconds just for the overhead of it. Compare that to how fast I can, say, `grep` the same file with a regex (`time` says 0m0.006s). 

Any ideas how to improve the performance story?

**Comment by juliangruber** [comment]
transpiled your coffeescript to vanilla javascript, because that's what most speak here, and what this project is written in:

```js
var input = FS.createReadStream(input_path);
var output = FS.createWriteStream(output_path);

var p = input;
p = p.pipe($split());

p = p.pipe(through2.obj(function(data, encoding, callback) {
  if (S.t0 == null) {
    start_profile(S);
    if (S.t0 == null) {
      S.t0 = Date.now();
    }
  }
  S.byte_count += data.length;
  S.item_count += +1;
  this.push(data);
  return callback();
}));

var _, i, ref;
for (_ = i = 1, ref = n; i <= ref; _ = i += +1) {
  if (mode === 'sync') {
    p = p.pipe(through2.obj(function(data, encoding, callback) {
      this.push(data);
      return callback();
    }));
  } else {
    p = p.pipe(through2.obj(function(data, encoding, callback) {
      return setImmediate((function(_this) {
        return function() {
          _this.push(data);
          return callback();
        };
      })(this));
    }));
  }
}

p = p.pipe(through2(function(data, encoding, callback) {
  this.push(data + '\n');
  return callback();
}));

p = p.pipe(output);
```

**Comment by juliangruber** [comment]
Can you provide us with a code example that doesn't use any external variables, like `S`, so others can run it too?

The `setImmediate` looks suspicious, why not push the data in the same tick?

And exactly which invocation of `through2` in your example are you referring to?

**Comment by loveencounterflow** [comment]
thanks for going through the trouble to convert my sample code to JS. Yes, it could've been more minimal, so here you go:

```js
var FS            = require 'fs';
var through2      = require 'through2';
var $split        = require 'binary-split';
var input_path    = 'test-data/Unicode-NamesList.txt';
var output_path   = '/dev/null';
var input         = FS.createReadStream(input_path);
var output        = FS.createWriteStream(output_path);
var n             = 50;
var $split
var p = input;
p = p.pipe($split());

var _, i, ref;
for (_ = i = 1, ref = n; i <= ref; _ = i += +1) {
    /* 1 */
    p = p.pipe(through2.obj(function(data, encoding, callback) {
      this.push(data);
      return callback();
    }));
  };
p = p.pipe(through2(function(data, encoding, callback) {
  this.push(data + '\n');
  return callback();
}));

p = p.pipe(output);
```


The `setImmediate` clause (here removed, would've been below line marked `1`) is just there to enable an asynchronous mode of operation. As can readily be gleaned from the [flamegraphs I posted](https://github.com/loveencounterflow/basic-stream-benchmarks#flamegraphs), using asynchronous in place of synchronous stream transforms has an absolutely huge effect on call stacks (unsurprisingly), but, [as the figures show](https://github.com/loveencounterflow/basic-stream-benchmarks#numbers), but a small effect on execution time (indeed, `setImmediate` would appear to introduce a little overhead itself). Full code at https://github.com/loveencounterflow/basic-stream-benchmarks/blob/master/lib/main.js#L165

"And exactly which invocation of through2 in your example are you referring to?"—not sure I understand your question. Thing is, the above processing pipeline consists of:

1) opening a read stream (for a file of 1,413,484 bytes of ASCII-only text);
2) splitting the byte chunks into (48,770) lines of text;
3) piping each line through `n` bare-bones, do-nothing transforms built with `through2`;
4) adding a newline character to each line; finally,
5) writing lines to `/dev/null`.

Now, step 3 is the critical one here. Again, [as the figures show](https://github.com/loveencounterflow/basic-stream-benchmarks#numbers), I can go through (no pun intended) the entire 1.4MB file in like under 2 seconds on my notebook (well over 0.5MB per second), but with a mere 20 or 40 no-op transforms (not a lot I'd say), that time quickly goes up to 10 or 20 seconds.

To rephrase this finding in a more user-oriented way: When processing text files of non-trivial, but still moderate size with a stream pipeline, be aware that as the length of your pipeline grows beyond a certain small limit (of less than 10 transforms), **your overall execution time will be dominated by the number of stream transforms**.

I'm doing little performance testing, so there may be some methodological blunders I'm not aware of; also, I'm lacking comparable data, so this is one reason to bring my findings here. Frankly, to me these results look a tad daunting, given that the streaming philosophy tells me to process my data in lots of little, focused steps. I have fully assimilated that approach, I find it great and software quality has greatly benefitted from it, but I wasn't prepared to this kind of overhead / loss of performance per stream transform added. Well, go ahead and, e.g., demonstrate that another approach that would likewise involve making (40 times 50,000 =) 2,000,000 no-op calls will suffer from a similar impact.

Coming to think of it, I'm going to try and write a non-streaming 'counter-test' to put those figures into perspective. But I believe I can say right away that making two million ordinary function calls is not going to take anywhere near 20 seconds on 'modern average' hardware (anyone have a single number to characterize the performance class of a given machine?).

**Comment by binki** [comment]
Maybe the overhead of streams themselves is just too much (as you found), especially as each stream step maintains its own buffers.

Transform streams is not the only way of splitting up a complex byte processing operation into small pieces. You can use something like transducers to combine a bunch of small tiny synchronous steps into one stream pipeline element. What streams and pipelines are good at are handling buffering/back-pressure, especially when one or more step in the pipeline is **asynchronous** and takes an unpredictable amount of time to complete.
