### ISSUE TITLE
please use a well known open source license

### ISSUE THREAD

**Issue by kapouer** [rvagg/through2#78]
MIT +no-false-attribs was cooked by the initial author of npm.
Since then he has switched almost all his work to ISC license.

Adding a custom clause to a license actually makes it a brand new
license, which interpretation is unforseeable unless you're a specialized lawyer.

In this special case of through2, it does seem be useful anyway.

**Comment by rvagg** [comment]
done

**Comment by kapouer** [comment]
Ha damn, the content of LICENSE is still the MIT+no-false-attribs !

**Comment by rvagg** [comment]
gack!

fixed, switched to markdown and assigned to additional contributors as well.
