### ISSUE TITLE
Hard to understand the code

### ISSUE THREAD

**Issue by LinBoLen** [rvagg/through2#87]
can you rewrite through2 with es6 to make it more comprehensible

reference: https://github.com/bornkiller/through-gulp

**Comment by specious** [comment]
@LinBoLen, how about a [bounty](https://www.bountysource.com/) to stoke some interest?

**Comment by rvagg** [comment]
yeah, this is probably not going to happen anyway because through2 needs to be maximally compatible, plus through2 is becoming even more trivial and you could achieve basically the same thing using pure node core streams and only a couple of lines these days (along with some ES6)
