### ISSUE TITLE
Create stream with independent objectModes for readableState and writeableState?

### ISSUE THREAD

**Issue by Slapbox** [rvagg/through2#93]
I'm trying to rewrite some code from `node@0.12.0` which looks like this (leaving out all the prototype and irrelevant code):

```js

function Input() {
    // Transform bytes...
    this._writableState.objectMode = false;
    // ...into objects.
    this._readableState.objectMode = true;
}

function Output() {
    this._writableState.objectMode = true;
    this._readableState.objectMode = false;
}

  function Transform(handler) {
    this._writableState.objectMode = true;
    this._readableState.objectMode = true;
}

```

How can I create a stream using `through2` which emulates these settings for a mixed object mode on the `input` and `output`?

----

In case it's relevant, here's some context for the above code (which as I mentioned leaves out a bunch of gunk I think is irrelevant to the question): 

```js
const nativeMessage = require('./theCodeShownAbove')

const input = new nativeMessage.Input();
const transform = new nativeMessage.Transform(messageHandler);
const output = new nativeMessage.Output();

process.stdin
  .pipe(input)
  .pipe(transform)
  .pipe(output)
  .pipe(process.stdout)
```

**Comment by rvagg** [comment]
Sorry @Slapbox, I don't know the answer to this off the top of my head, it sounds like you might be over-complicating it a bit and should consider simplifying.

You could try asking over at nodejs/help and maybe getting someone from the current streams team to answer.

**Comment by Slapbox** [comment]
Thanks for your reply @rvagg!

I don't exactly remember, but I'm pretty sure I was over-complicating things.
