### ISSUE TITLE
`this.push` method call other object stream function

### ISSUE THREAD

**Issue by qinyuanbin** [rvagg/through2#98]
I was curious in this code, is it correct?
 
```js
        gulp.src(somefiles)
            .pipe(through2.obj(function(f, enc, callback) {
                console.log(1)
                this.push(f);
                console.log(4)
                return callback();
            }))
            .pipe(through2.obj(function(f, enc, callback) {
                console.log(2)
                this.push(f);
                console.log(3)
                return callback();
            }))
```

expected:
```js
1
4
2
3
```

but:
```js
1
2
3
4
```

**Comment by rvagg** [comment]
intuitively I would have expected the same output as you, but if you're gtting the second then I guess that means there's no deferral between a `push()` and the next stream getting the chunk. Maybe Matteo will chime in if he's seeing this notification (maybe not, he's pretty busy) as he's much more intimately involved in Node core streams design these days than I am.
I don't see a reason that this non-deferral might be a bad implementation choice for streams, it's good for efficiency at least, but if it's a problem for you then maybe manually defer it, `process.nextTick(() => callback(null, f))` (`callback()` can be used for single chunks in lieu of `push()` btw).
